from typing import ClassVar

from sqladmin import ModelView

from apps.auth.models.verification import VerificationCode


class VerificationCodeAdmin(ModelView, model=VerificationCode):
    name = "Verification Code"
    name_plural = "Verification Codes"
    icon = "fa-solid fa-envelope-circle-check"

    column_list: ClassVar = [
        VerificationCode.id,
        VerificationCode.user_id,
        VerificationCode.code,
        VerificationCode.used,
        VerificationCode.expires_at,
    ]
    column_sortable_list: ClassVar = [
        VerificationCode.id,
        VerificationCode.user_id,
        VerificationCode.used,
        VerificationCode.expires_at,
    ]
    column_searchable_list: ClassVar = [VerificationCode.code]

    # Codes are generated by the signup flow, not created by hand.
    can_create = False
    can_edit = False
